# Generated by Django 4.1.6 on 2023-02-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projcts'),
    ]

    operations = [
        migrations.AddField(
            model_name='projcts',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
