# Generated by Django 3.2.7 on 2021-09-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='ser_image')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
    ]
