# Generated by Django 3.2.7 on 2021-09-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='p_parcent',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
